%YAML:1.0
---
detect_thresh: 0.5
sigma: 0.2
lambda: 0.0001
interp_factor: 0.075
output_sigma_factor: 0.125
resize: 0
max_patch_size: 6400
split_coeff: 1
wrap_kernel: 0
desc_npca: 1
desc_pca: 2
compress_feature: 1
compressed_size: 2
pca_learning_rate: 0.15
