sigma_hog: 0.6
sigma_grey_scale: 0.2
lambdar: 0.0001
padding: 4.5
output_sigma_factor: 0.125
template_size_multiscale: 96
template_size_fixed_window: 96
template_size_else: 1
interp_factor_hog: 0.0000125
interp_factor_grey_scale: 0.075
cell_size_hog: 4
cell_size_grey_scale: 1
scale_step_multiscale: 1.05
scale_step_fixed_window: 1
scale_step_else: 1
scale_weight_multiscale: 0.96
num_sector: 9
flt_epsilon: 0.0000001
